version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      vue:
        patterns: ["vue", "vue-tsc", "@vitejs/plugin-vue", "@vue/tsconfig"]
      vite:
        patterns: ["vite"]
      firebase:
        patterns: ["firebase"]
      ui:
        patterns: ["naive-ui"]
